import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html className={'flex flex-col items-center'} lang="en">
      <title>blog markdown</title>
      <body className={`${inter.className} w-[80%] flex flex-col justify-center items-center`}>
      <Header />
      <div className="flex flex-col items-center w-full px-6 sm:px-7 lg:px-9">
        {children}
      </div>
      <Footer />
      </body>
      </html>
  );
}
